[package]
name = "cli"
version = "0.1.0"
authors = ["primozpadar <primoz.padar1@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0.78"
